service: ive-authorizer
provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  region: ${self:custom.pRegion}
  role: arn:aws:iam::${self:custom.pAccount}:role/${self:custom.pRole}
  memorySize: 256
  Timeout: 5
  deploymentBucket:
    name: ${self:custom.pDeploymentBucketName}
    tags:
      name: ${self:service}
      project: IVE
  deploymentPrefix: serverless

functions:
  authorizer:
    name: ive${self:custom.pFunction}-authorizer
    handler: dist/ive-authorizer.handler
    environment:
      ive_lambda_env: ${self:provider.stage}
      validate_token_url_dev: https://login.microsoftonline.com/00000000000/discovery/v2.0/keys
      validate_token_url_qa: https://login.microsoftonline.com/00000000000/discovery/v2.0/keys
      validate_token_url_prod: https://login.microsoftonline.com/00000000000/discovery/v2.0/keys      

custom:
  # Region Map for deployment of lambda functions.
  dev-region: us-west-2
  qa-region: us-west-2
  prod-region: us-east-1

  dev-function: -dev
  qa-function: -qa
  prod-function: ''
  pFunction: ${self:custom.${self:custom.pEnvironment}-function}

  dev-deploymentBucketName: ${self:provider.stage}.ive.toyota.com-data
  qa-deploymentBucketName: ${self:provider.stage}.ive.toyota.com-data
  prod-deploymentBucketName: ive.toyota.com-data
  pDeploymentBucketName: ${self:custom.${self:custom.pEnvironment}-deploymentBucketName}

  # AWS account
  # add account
  dev-account: 00000000000
  qa-account: 00000000000
  prod-account: 00000000000

  dev-role: AWSServiceForLamda
  qa-role: AWSServiceForLamda
  # qa-role: ive-qa-lambda-role
  prod-role: ive-prod-lambda-role

  pRole: ${self:custom.${self:custom.pEnvironment}-role}
  
  pEnvironment: ${opt:stage, self:provider.stage}
  pRegion: ${self:custom.${self:custom.pEnvironment}-region}
  pAccount: ${self:custom.${self:custom.pEnvironment}-account}

  environment:
    ive_lambda_env: ${self:provider.stage}
    stages:
      - dev
      - qa
      - prod
package:
  excludeDevDependencies: true
  exclude:
    - ./*.json
    - /*.zip
    - ./*.zip
    - ./.json
    - ./.js
    # - node_modules/**
    # - '!node_modules/ssh2-sftp-client/**'
    # - '!node_modules/pg/**'
    # - '!node_modules/ssh2/**'
    # - '!node_modules/ssh2-streams/**'
    # - '!node_modules/concat-stream/**'
    # - '!node_modules/retry/**'

