service: ive-authorizer
provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  region: ${self:custom.pRegion}
  role: arn:aws:iam::${self:custom.pAccount}:role/AWSServiceForLamda
  Timeout: 900
  deploymentBucket:
    name: ${self:provider.stage}.avp.ive.toyota.com-data
    tags:
      name: ${self:service}
      project: AVP
  deploymentPrefix: serverless

functions:
  authorizer:
    name: ${self:service}-${self:provider.stage}
    handler: apv-authorizer.handler
    environment:
      apv_lambda_env: ${self:provider.stage}
      validate_token_url_dev: https://login.microsoftonline.com/9107b728-2166-4e5d-8d13-d1ffdf0351ef/discovery/v2.0/keys
      validate_token_url_qa: https://login.microsoftonline.com/9107b728-2166-4e5d-8d13-d1ffdf0351ef/discovery/v2.0/keys
      validate_token_url_prod: https://login.microsoftonline.com/9107b728-2166-4e5d-8d13-d1ffdf0351ef/discovery/v2.0/keys

custom:
  dev-region: us-west-2
  qa-region: us-west-2
  prod-region: us-west-1
  pEnvironment: ${opt:stage, self:provider.stage}
  pRegion: ${self:custom.${self:custom.pEnvironment}-region}
  dev-account: 782894107121
  qa-account: 782894107121
  prod-account: 782894107121
  pAccount: ${self:custom.${self:custom.pEnvironment}-account}
  environment:
    apv_lambda_env: ${self:provider.stage}
    stages:
      - dev
      - qa
      - prod
